version: '3'

services:
  users_server: 
    container_name: users_server
    build:
      context: ../users
      dockerfile: Dockerfile
    ports:
      - "5300:5300"

  api:
    container_name: api_server
    depends_on:
      - users_server
    build:
      context: ../api
      dockerfile: Dockerfile
    ports:
      - "80:80"